this.home = 'Alnilam';
this.galaxies = [
    {name:'Girtab',destinations:['Lambda Velorum','Alhena','Bellatrix','Sadr','Deneb','Alpha Centauri B','Antares','Betelgeuse']},
    {name:'Achernar',destinations:['Wei','Caph','Atria','Ankaa','Ras Alhague','Aldebaran','Alderamin','Delta Velorum']},
    {name:'Mimosa',destinations:['Castor A','Arcturus','Alpha Centauri A','Shaula','Acrux B','Saiph','Alpha Lupi','Capella B']},
    {name:'Denebola',destinations:['Phecda','Mirfak','Rigel','Alnitak A','Dschubba','Canopus','Mirach','Beta Gruis']},
    {name:'Procyon',destinations:['Gienah','Alphard','Murzim','Regulus','Wezen','Aspidiske','Almach','Gacrux']},
    {name:'Caph',destinations:['Delta Velorum','Wei','Ankaa','Atria','Aldebaran','Achernar','Alderamin','Ras Alhague']},
    {name:'Aspidiske',destinations:['Regulus','Deneb Kaitos','Alphard','Almach','Gacrux','Procyon','Murzim','Gienah']},
    {name:'Atria',destinations:['Wei','Delta Velorum','Achernar','Aldebaran','Alderamin','Ankaa','Ras Alhague','Caph']},
    {name:'Algieba',destinations:['Sun','Sirius','Peacock','Bellatrix','Altair','Gamma Cassiopeiae','Fomalhaut','Polaris']},
    {name:'Alphard',destinations:['Wezen','Aspidiske','Procyon','Almach','Gacrux','Gienah','Regulus','Murzim']},
    {name:'Acrux B',destinations:['Mimosa','Saiph','Castor A','Arcturus','Alpha Centauri A','Shaula','Epsilon Centauri','Capella B']},
    {name:'Alpha Centauri A',destinations:['Saiph','Castor A','Epsilon Centauri','Mimosa','Arcturus','Acrux B','Shaula','Capella B']},
    {name:'Arcturus',destinations:['Shaula','Alpha Centauri A','Capella B','Saiph','Acrux B','Mimosa','Castor A','Epsilon Centauri']},
    {name:'Capella B',destinations:['Mimosa','Castor A','Alpha Centauri A','Shaula','Arcturus','Epsilon Centauri','Acrux B','Saiph']},
    {name:'Gamma2 Velorum',destinations:['Schedar','Alnilam','Menkent','Enif','Eta Centauri','Alpha Lupi','El Nath','Zeta Puppis']},
    {name:'Gienah',destinations:['Alphard','Regulus','Procyon','Aspidiske','Murzim','Almach','Gacrux','Wezen']},
    {name:'Peacock',destinations:['Sirius','Polaris','Algieba','Bellatrix','Sun','Gamma Cassiopeiae','Fomalhaut','Altair']},
    {name:'Zeta Puppis',destinations:['Gamma2 Velorum','Alpha Lupi','Enif','Alnilam','Eta Centauri','El Nath','Menkent','Schedar']},
    {name:'Kochab',destinations:['Alpheratz','Miaplacidus','Scheat','Kaus Australis','Avior','Etamin','Vega','Markab']},
    {name:'Mirfak',destinations:['Rigel','Alnitak A','Mirach','Phecda','Dschubba','Canopus','Beta Gruis','Denebola']},
    {name:'Alhena',destinations:['Antares','Deneb Kaitos','Deneb','Lambda Velorum','Sadr','Betelgeuse','Girtab','Alpha Centauri B']},
    {name:'Epsilon Centauri',destinations:['Alpha Centauri A','Capella B','Shaula','Saiph','Arcturus','Acrux B','Polaris','Castor A']},
    {name:'Menkent',destinations:['Schedar','Gamma2 Velorum','Eta Centauri','Alpha Lupi','El Nath','Enif','Zeta Puppis','Alnilam']},
    {name:'Sadr',destinations:['Alhena','Lambda Velorum','Alpha Centauri B','Girtab','Deneb Kaitos','Betelgeuse','Deneb','Antares']},
    {name:'Almach',destinations:['Procyon','Alphard','Wezen','Gacrux','Gienah','Aspidiske','Regulus','Murzim']},
    {name:'El Nath',destinations:['Alnilam','Enif','Menkent','Rigel','Zeta Puppis','Gamma2 Velorum','Schedar','Eta Centauri']},
    {name:'Antares',destinations:['Lambda Velorum','Deneb','Alpha Centauri B','Alhena','Girtab','Sadr','Betelgeuse','Deneb Kaitos']},
    {name:'Canopus',destinations:['Rigel','Phecda','Denebola','Mirfak','Mirach','Beta Gruis','Alnitak A','Dschubba']},
    {name:'Eta Centauri',destinations:['Alnilam','El Nath','Menkent','Gamma2 Velorum','Enif','Schedar','Zeta Puppis','Alpha Lupi']},
    {name:'Vega',destinations:['Alpheratz','Markab','Scheat','Kochab','Avior','Etamin','Kaus Australis','Miaplacidus']},
    {name:'Castor A',destinations:['Alpha Centauri A','Shaula','Capella B','Mimosa','Arcturus','Epsilon Centauri','Acrux B','Saiph']},
    {name:'Schedar',destinations:['Gamma2 Velorum','Alpha Lupi','El Nath','Alnilam','Menkent','Enif','Eta Centauri','Zeta Puppis']},
    {name:'Alderamin',destinations:['Aldebaran','Wei','Atria','Ankaa','Caph','Delta Velorum','Alnitak A','Achernar']},
    {name:'Gamma Cassiopeiae',destinations:['Altair','Sirius','Polaris','Algieba','Sun','Fomalhaut','Bellatrix','Peacock']},
    {name:'Betelgeuse',destinations:['Lambda Velorum','Deneb','Girtab','Deneb Kaitos','Antares','Sadr','Alhena','Alpha Centauri B']},
    {name:'Shaula',destinations:['Epsilon Centauri','Acrux B','Alpha Centauri A','Saiph','Capella B','Mimosa','Castor A','Arcturus']},
    {name:'Polaris',destinations:['Epsilon Centauri','Altair','Sirius','Gamma Cassiopeiae','Sun','Peacock','Fomalhaut','Algieba']},
    {name:'Alpha Centauri B',destinations:['Sadr','Deneb','Lambda Velorum','Antares','Deneb Kaitos','Betelgeuse','Girtab','Alhena']},
    {name:'Dschubba',destinations:['Rigel','Denebola','Mirach','Mirfak','Alnitak A','Beta Gruis','Phecda','Canopus']},
    {name:'Wezen',destinations:['Gacrux','Almach','Regulus','Procyon','Gienah','Alphard','Markab','Murzim']},
    {name:'Altair',destinations:['Fomalhaut','Algieba','Bellatrix','Sirius','Gamma Cassiopeiae','Sun','Polaris','Peacock']},
    {name:'Avior',destinations:['Markab','Vega','Scheat','Etamin','Kaus Australis','Miaplacidus','Alpheratz','Kochab']},
    {name:'Bellatrix',destinations:['Girtab','Peacock','Fomalhaut','Sirius','Altair','Algieba','Sun','Gamma Cassiopeiae']},
    {name:'Rigel',destinations:['Mirfak','Canopus','Mirach','Phecda','Beta Gruis','El Nath','Dschubba','Denebola']},
    {name:'Aldebaran',destinations:['Delta Velorum','Ras Alhague','Caph','Ankaa','Achernar','Atria','Wei','Alderamin']},
    {name:'Beta Gruis',destinations:['Phecda','Dschubba','Rigel','Alnitak A','Canopus','Mirach','Denebola','Mirfak']},
    {name:'Alnitak A',destinations:['Denebola','Dschubba','Mirach','Canopus','Mirfak','Phecda','Beta Gruis','Alderamin']},
    {name:'Enif',destinations:['Gamma2 Velorum','Zeta Puppis','Alpha Lupi','Eta Centauri','El Nath','Schedar','Alnilam','Menkent']},
    {name:'Ankaa',destinations:['Atria','Delta Velorum','Achernar','Wei','Caph','Ras Alhague','Alderamin','Aldebaran']},
    {name:'Saiph',destinations:['Epsilon Centauri','Castor A','Mimosa','Capella B','Arcturus','Acrux B','Shaula','Alpha Centauri A']},
    {name:'Phecda',destinations:['Mirfak','Alnitak A','Mirach','Dschubba','Beta Gruis','Denebola','Canopus','Rigel']},
    {name:'Fomalhaut',destinations:['Sirius','Altair','Sun','Algieba','Polaris','Bellatrix','Gamma Cassiopeiae','Peacock']},
    {name:'Alpheratz',destinations:['Etamin','Vega','Miaplacidus','Markab','Kaus Australis','Scheat','Avior','Kochab']},
    {name:'Etamin',destinations:['Avior','Alpheratz','Kaus Australis','Vega','Kochab','Scheat','Markab','Miaplacidus']},
    {name:'Markab',destinations:['Kochab','Etamin','Alpheratz','Vega','Scheat','Avior','Kaus Australis','Wezen']},
    {name:'Alnilam',destinations:['Eta Centauri','El Nath','Gamma2 Velorum','Menkent','Enif','Zeta Puppis','Schedar','Alpha Lupi']},
    {name:'Mirach',destinations:['Alnitak A','Denebola','Beta Gruis','Rigel','Dschubba','Canopus','Phecda','Mirfak']},
    {name:'Sun',destinations:['Gamma Cassiopeiae','Fomalhaut','Sirius','Altair','Peacock','Polaris','Bellatrix','Algieba']},
    {name:'Kaus Australis',destinations:['Markab','Miaplacidus','Alpheratz','Scheat','Etamin','Avior','Vega','Kochab']},
    {name:'Miaplacidus',destinations:['Kaus Australis','Etamin','Ras Alhague','Vega','Avior','Scheat','Kochab','Alpheratz']},
    {name:'Scheat',destinations:['Etamin','Avior','Miaplacidus','Kochab','Alpheratz','Markab','Kaus Australis','Vega']},
    {name:'Delta Velorum',destinations:['Alderamin','Caph','Atria','Ras Alhague','Wei','Aldebaran','Achernar','Ankaa']},
    {name:'Lambda Velorum',destinations:['Deneb','Antares','Betelgeuse','Sadr','Alpha Centauri B','Girtab','Deneb Kaitos','Alhena']},
    {name:'Murzim',destinations:['Wezen','Gacrux','Almach','Regulus','Procyon','Gienah','Aspidiske','Alphard']},
    {name:'Sirius',destinations:['Fomalhaut','Sun','Altair','Bellatrix','Gamma Cassiopeiae','Polaris','Peacock','Algieba']},
    {name:'Deneb',destinations:['Antares','Alpha Centauri B','Alhena','Sadr','Betelgeuse','Deneb Kaitos','Girtab','Lambda Velorum']},
    {name:'Regulus',destinations:['Murzim','Aspidiske','Almach','Alphard','Wezen','Procyon','Gacrux','Gienah']},
    {name:'Gacrux',destinations:['Regulus','Procyon','Murzim','Alphard','Aspidiske','Almach','Gienah','Wezen']},
    {name:'Deneb Kaitos',destinations:['Alhena','Sadr','Betelgeuse','Deneb','Lambda Velorum','Alpha Centauri B','Antares','Aspidiske']},
    {name:'Ras Alhague',destinations:['Aldebaran','Wei','Miaplacidus','Delta Velorum','Caph','Atria','Ankaa','Achernar']},
    {name:'Alpha Lupi',destinations:['Zeta Puppis','Schedar','Eta Centauri','Mimosa','Alnilam','Gamma2 Velorum','Menkent','Enif']},
    {name:'Wei',destinations:['Achernar','Caph','Delta Velorum','Ras Alhague','Atria','Ankaa','Aldebaran','Alderamin']}
];
